name: leancode_forms
description: A package for managing form state based on BLoC.
version: 0.0.1
homepage: https://github.com/leancodepl/leancode_forms.git

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: '>=3.10.0'

dependencies:
  bloc_test: ^9.1.4
  collection: ^1.17.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^6.0.0


flutter: